name: "Vito"
version: "1.0.4"
slug: "vito"
description: "Run the Vito deployment platform inside Home Assistant with Ingress support"
url: "https://github.com/vitodeploy/vito"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:application
map:
  - config:rw
  - data:rw
options:
  app_key: ""
  name: "vito"
  email: "vito@example.com"
  password: "password"
  app_url: "http://homeassistant.local"
schema:
  app_key: str?
  name: str
  email: str
  password: str
  app_url: str
