name: "Vito"
version: "1.3.0"
slug: "vito"
description: "Vito web interface inside Home Assistant"
arch:
  - amd64
startup: services
boot: auto
host_network: true
map:
  - config:rw
  - share:rw
  - ssl:ro
  - media:rw
options:
  app_key: "your-32-character-app-key"
  name: "vito"
  email: "vito@example.com"
  password: "password"
  app_url: "http://localhost:8000"
schema:
  app_key: str
  name: str
  email: str
  password: str
  app_url: str
