name: "Vito"
version: "3.1.3"
slug: "vito"
description: "Vito web interface inside Home Assistant"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
ingress: true
ingress_port: 80
ingress_entry: /
panel_icon: mdi:server
ports:
  80/tcp: 8089
ports_description:
  80/tcp: "Vito web interface (direct access)"
map:
  - config:rw
  - share:rw
  - ssl:ro
  - media:rw
  - addon_config:rw
options:
  name: "vito"
  email: "admin@example.com"
  password: "password"
schema:
  name: "str?"
  email: "str?"
  password: "str?"
