name: "Vito"
version: "1.7.4"
slug: "vito"
description: "Vito web interface inside Home Assistant"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
ingress: true
ingress_port: 80
ingress_entry: /
panel_icon: mdi:server
ports:
  80/tcp: null
ports_description:
  80/tcp: "Web interface (not needed with ingress)"
map:
  - config:rw
  - share:rw
  - ssl:ro
  - media:rw
options:
  app_key: "base64:YOUR-32-CHARACTER-KEY-HERE"
  name: "vito"
  email: "admin@example.com"
  password: "password"
  app_url: "http://homeassistant.local:8123"
schema:
  app_key: str
  name: str
  email: str
  password: str
  app_url: str
