name: Vito
version: "5.0.1"
slug: vito
description: Vito app running inside Home Assistant
arch:
  - amd64
  - armv7
  - aarch64
  - i386
startup: services
boot: auto
ports:
  8000/tcp: 8089
map:
  - config:rw
options:
  app_key: "your-32-character-app-key"
  name: "vito"
  email: "vito@example.com"
  password: "password"
  app_url: "http://localhost:8000"
schema:
  app_key: str
  name: str
  email: str
  password: str
  app_url: str
