name: "Tolgee"
version: "1.0.0"
slug: "tolgee"
description: "Tolgee localization platform for Home Assistant"
url: "https://tolgee.io/"
arch:
  - amd64
  - arm64
startup: services
init: false
ports:
  8080/tcp: 8080
options:
  database_url: "jdbc:postgresql://core-postgres:5432/tolgee"
  database_user: "tolgee"
  database_password: "tolgee"
schema:
  database_url: str
  database_user: str
  database_password: str
