name: Supernote Private Cloud
version: "1.2.5"
slug: supernote_private_cloud
description: "Private cloud solution for Supernote devices with file sync and management"
url: "https://github.com/supernote-community/supernote-private-cloud-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
map:
  - share:rw
  - addon_config:rw
  - ssl:ro
  - media:rw
options:
  mysql_root_password: "SupernoteRoot2025!"
  mysql_password: "SupernoteUser2025!"
  redis_password: "RedisSupernote2025!"
  log_level: "info"
  ssl_enabled: false
  ssl_certfile: ""
  ssl_keyfile: ""
  backup_enabled: true
  max_file_size: "104857600"
  session_timeout: "3600"
schema:
  mysql_root_password: "password"
  mysql_password: "password"
  redis_password: "password"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  ssl_enabled: "bool"
  ssl_certfile: "str?"
  ssl_keyfile: "str?"
  backup_enabled: "bool"
  max_file_size: "int(1,1073741824)"
  session_timeout: "int(300,86400)"
ports:
  19072/tcp: 19072
  19071/tcp: null
  8080/tcp: null
  9888/tcp: null
  6000/tcp: null
ports_description:
  19072/tcp: "Supernote Web Interface"
  19071/tcp: "Backend API (Internal)"
  8080/tcp: "Web Service (Internal)"
  9888/tcp: "Frontend Service (Internal)"
  6000/tcp: "Notelib Service (Internal)"
webui: "http://[HOST]:[PORT:19072]"
panel_icon: mdi:cloud-upload
panel_title: "Supernote Cloud"
hassio_api: true
hassio_role: default
privileged:
  - SYS_ADMIN
devices:
  - /dev/fuse
apparmor: false
stage: stable
# image: "ghcr.io/supernote-community/{arch}-supernote-private-cloud"
